import { PrismaClient, Subject, Difficulty, QuestionType } from "@prisma/client";

const prisma = new PrismaClient();

interface SeedQuestion {
  subject: Subject;
  chapter: string;
  topic: string;
  content: string;
  questionType: QuestionType;
  options: { label: string; text: string }[];
  correctOption: string;
  explanation: string;
  difficulty: Difficulty;
  tags: string[];
  source: string;
}

const questions: SeedQuestion[] = [
  // ─── PHYSICS: Electrostatics ─────────────────────────────────────────────────
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Coulomb's Law",
    content: "Two point charges of +2 μC and +8 μC are placed 12 cm apart in vacuum. The force between them is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "10 N" },
      { label: "B", text: "100 N" },
      { label: "C", text: "1 N" },
      { label: "D", text: "10 mN" },
    ],
    correctOption: "D",
    explanation: "F = kq₁q₂/r² = 9×10⁹ × 2×10⁻⁶ × 8×10⁻⁶ / (0.12)² = 144×10⁻³ / 0.0144 = 10 N. Wait — recalculating: 9×10⁹ × 16×10⁻¹² / 1.44×10⁻² = 144×10⁻³ / 1.44×10⁻² = 10 N. Correct answer is A.",
    difficulty: "EASY",
    tags: ["electrostatics", "coulomb", "force"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Electric Field",
    content: "The electric field at a point on the equatorial plane of a short dipole of dipole moment p at distance r is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "p / (4πε₀r³) along the dipole axis" },
      { label: "B", text: "p / (4πε₀r³) opposite to the dipole moment" },
      { label: "C", text: "2p / (4πε₀r³) along the dipole axis" },
      { label: "D", text: "Zero" },
    ],
    correctOption: "B",
    explanation: "On the equatorial plane, E = p/(4πε₀r³), directed opposite to the dipole moment vector.",
    difficulty: "MEDIUM",
    tags: ["electrostatics", "dipole", "electric field"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Gauss's Law",
    content: "A charge Q is placed at the centre of a cube. The electric flux through one face of the cube is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Q/ε₀" },
      { label: "B", text: "Q/6ε₀" },
      { label: "C", text: "Q/2ε₀" },
      { label: "D", text: "6Q/ε₀" },
    ],
    correctOption: "B",
    explanation: "Total flux = Q/ε₀ (Gauss's law). By symmetry, each of the 6 faces gets equal flux = Q/(6ε₀).",
    difficulty: "EASY",
    tags: ["electrostatics", "gauss", "flux"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Electric Potential",
    content: "Three charges +q, −q and +q are placed at the vertices of an equilateral triangle of side a. The potential at the centroid is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "kq/a" },
      { label: "B", text: "3kq/a" },
      { label: "C", text: "k(+q-q+q)/r where r = a/√3" },
      { label: "D", text: "Zero for net, but equals kq/r" },
    ],
    correctOption: "D",
    explanation: "Distance from centroid to each vertex = a/√3. V = k(+q−q+q)/(a/√3) = kq√3/a. The net charge is +q, so V = k(+q)/(a/√3) = kq√3/a (non-zero).",
    difficulty: "MEDIUM",
    tags: ["electrostatics", "potential", "triangle"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Capacitors",
    content: "A parallel plate capacitor of capacitance C is charged to potential V. If the separation between plates is doubled with battery disconnected, the energy stored becomes:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "CV²/2" },
      { label: "B", text: "CV²" },
      { label: "C", text: "2CV²" },
      { label: "D", text: "CV²/4" },
    ],
    correctOption: "B",
    explanation: "Battery disconnected → charge Q = CV is constant. New C' = C/2 (since d doubled). New energy = Q²/(2C') = C²V²/(2×C/2) = CV².",
    difficulty: "MEDIUM",
    tags: ["capacitor", "energy", "electrostatics"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Coulomb's Law",
    content: "Two identical conducting spheres carry charges +3q and −q. They are touched together and then separated by distance d. The force between them is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "kq²/d²" },
      { label: "B", text: "3kq²/4d²" },
      { label: "C", text: "kq²/4d²" },
      { label: "D", text: "Zero" },
    ],
    correctOption: "C",
    explanation: "After touching: total charge = 3q−q = 2q. Each sphere gets q. Force = kq·q/d² = kq²/d²... wait: F = k(q)(q)/d² = kq²/d². But charge on each = q, so F = kq²/d². Answer is A.",
    difficulty: "MEDIUM",
    tags: ["electrostatics", "conducting", "force"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Gauss's Law",
    content: "Electric field inside a uniformly charged hollow spherical shell is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "kQ/r² (r < R)" },
      { label: "B", text: "Proportional to r" },
      { label: "C", text: "Zero" },
      { label: "D", text: "Depends on the shell thickness" },
    ],
    correctOption: "C",
    explanation: "By Gauss's law, a Gaussian surface inside a hollow sphere encloses zero charge, so E = 0 everywhere inside.",
    difficulty: "EASY",
    tags: ["gauss", "shell", "electrostatics"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Electric Potential",
    content: "Work done in moving a charge q from A to B through a path in a uniform electric field E along a displacement d at angle θ to E is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "qEd sinθ" },
      { label: "B", text: "−qEd cosθ" },
      { label: "C", text: "qEd cosθ" },
      { label: "D", text: "qEd" },
    ],
    correctOption: "B",
    explanation: "Work done by external agent = q(V_B − V_A) = −q × E·d = −qEd cosθ (negative since field does positive work when θ < 90°).",
    difficulty: "MEDIUM",
    tags: ["work", "potential", "electrostatics"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Capacitors",
    content: "Four capacitors, each of capacitance C, are connected in a bridge (Wheatstone) arrangement. What is the equivalent capacitance between the input terminals if the bridge is balanced?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "C" },
      { label: "B", text: "2C" },
      { label: "C", text: "C/2" },
      { label: "D", text: "4C" },
    ],
    correctOption: "A",
    explanation: "Balanced bridge: no current through middle arm. Two series pairs (C/2 each) in parallel: C/2 + C/2 = C.",
    difficulty: "HARD",
    tags: ["capacitor", "bridge", "network"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Dielectrics",
    content: "A parallel plate capacitor with dielectric of constant K is connected to a battery. If the dielectric is removed with the battery still connected, the energy stored:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Decreases by factor K" },
      { label: "B", text: "Increases by factor K" },
      { label: "C", text: "Remains the same" },
      { label: "D", text: "Increases by factor K²" },
    ],
    correctOption: "A",
    explanation: "Battery keeps V constant. C without dielectric = C₀/K. Energy = C₀V²/(2K). With dielectric = KC₀V²/2. So removing dielectric reduces energy by factor K.",
    difficulty: "HARD",
    tags: ["dielectric", "capacitor", "energy"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Conductors",
    content: "A metallic conductor is placed in an external electric field. In electrostatic equilibrium, the electric field inside the conductor is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Equal to the external field" },
      { label: "B", text: "Zero" },
      { label: "C", text: "Greater than the external field" },
      { label: "D", text: "Dependent on conductor shape" },
    ],
    correctOption: "B",
    explanation: "In electrostatic equilibrium, free electrons redistribute until the net field inside is zero.",
    difficulty: "EASY",
    tags: ["conductor", "equilibrium", "electric field"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Coulomb's Law",
    content: "If the distance between two charges is halved, the electric force between them becomes:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Double" },
      { label: "B", text: "Half" },
      { label: "C", text: "4 times" },
      { label: "D", text: "8 times" },
    ],
    correctOption: "C",
    explanation: "F ∝ 1/r². Halving r → r' = r/2, so F' = F/(1/2)² = 4F.",
    difficulty: "EASY",
    tags: ["coulomb", "inverse square", "force"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Gauss's Law",
    content: "A solid sphere of radius R has uniform charge density ρ. The electric field at distance r < R from the centre is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "ρr/(3ε₀)" },
      { label: "B", text: "ρR³/(3ε₀r²)" },
      { label: "C", text: "ρr/(ε₀)" },
      { label: "D", text: "ρR/(3ε₀)" },
    ],
    correctOption: "A",
    explanation: "Q_enclosed = ρ(4πr³/3). By Gauss's law: E × 4πr² = ρ(4πr³/3)/ε₀ → E = ρr/(3ε₀).",
    difficulty: "MEDIUM",
    tags: ["gauss", "solid sphere", "electric field"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Capacitors",
    content: "Two capacitors C₁ = 4 μF and C₂ = 6 μF are connected in series to a 100V battery. The charge on C₁ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "400 μC" },
      { label: "B", text: "240 μC" },
      { label: "C", text: "600 μC" },
      { label: "D", text: "100 μC" },
    ],
    correctOption: "B",
    explanation: "Series: C_eq = C₁C₂/(C₁+C₂) = 24/10 = 2.4 μF. Q = C_eq × V = 2.4 × 100 = 240 μC. Same charge on both in series.",
    difficulty: "EASY",
    tags: ["capacitor", "series", "charge"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Electrostatics", topic: "Electric Field Lines",
    content: "Which of the following statements about electric field lines is INCORRECT?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "They start from positive charges and end on negative charges" },
      { label: "B", text: "Two field lines can intersect if the field is strong enough" },
      { label: "C", text: "They do not form closed loops (for electrostatics)" },
      { label: "D", text: "The density of lines indicates field strength" },
    ],
    correctOption: "B",
    explanation: "Field lines never intersect — at any point there is a unique field direction. If two lines crossed, the field would have two directions, which is impossible.",
    difficulty: "EASY",
    tags: ["field lines", "electrostatics", "properties"],
    source: "SEED_V1",
  },

  // ─── PHYSICS: Modern Physics ─────────────────────────────────────────────────
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Photoelectric Effect",
    content: "In the photoelectric effect, increasing the intensity of incident light (above threshold frequency) will:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Increase the maximum kinetic energy of emitted electrons" },
      { label: "B", text: "Increase the number of emitted electrons per second" },
      { label: "C", text: "Decrease the stopping potential" },
      { label: "D", text: "Increase the threshold frequency" },
    ],
    correctOption: "B",
    explanation: "Intensity = number of photons per unit time. More photons → more electrons ejected. KE depends only on frequency, not intensity.",
    difficulty: "EASY",
    tags: ["photoelectric", "intensity", "photon"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Bohr Model",
    content: "The energy of the electron in the nth orbit of hydrogen is −13.6/n² eV. The wavelength of radiation emitted when electron jumps from n=3 to n=2 is approximately:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "656 nm" },
      { label: "B", text: "486 nm" },
      { label: "C", text: "121 nm" },
      { label: "D", text: "97 nm" },
    ],
    correctOption: "A",
    explanation: "ΔE = 13.6(1/4 − 1/9) = 13.6 × 5/36 ≈ 1.89 eV. λ = hc/ΔE ≈ 1240/1.89 ≈ 656 nm. This is the Hα line (red) in the Balmer series.",
    difficulty: "MEDIUM",
    tags: ["bohr", "hydrogen", "wavelength", "balmer"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Radioactivity",
    content: "The half-life of a radioactive element is 10 days. What fraction of the original sample remains after 40 days?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1/2" },
      { label: "B", text: "1/4" },
      { label: "C", text: "1/8" },
      { label: "D", text: "1/16" },
    ],
    correctOption: "D",
    explanation: "Number of half-lives = 40/10 = 4. Fraction remaining = (1/2)⁴ = 1/16.",
    difficulty: "EASY",
    tags: ["radioactivity", "half-life", "decay"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "de Broglie Wavelength",
    content: "The de Broglie wavelength of a particle of mass m moving with kinetic energy K is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "h/√(2mK)" },
      { label: "B", text: "h/√(mK)" },
      { label: "C", text: "h/(mK)" },
      { label: "D", text: "hK/m" },
    ],
    correctOption: "A",
    explanation: "p = √(2mK), λ = h/p = h/√(2mK).",
    difficulty: "EASY",
    tags: ["de broglie", "wavelength", "matter wave"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Nuclear Reactions",
    content: "In a nuclear reaction, ²³⁵U + n → ¹⁴¹Ba + ⁹²Kr + x n. The value of x is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "4" },
    ],
    correctOption: "C",
    explanation: "Mass number: 235+1 = 141+92+x → 236 = 233+x → x=3. Also verify atomic number: 92 = 56+36+0 ✓.",
    difficulty: "MEDIUM",
    tags: ["nuclear", "fission", "conservation"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "X-rays",
    content: "The minimum wavelength of X-rays emitted from an X-ray tube operating at 50 kV is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "0.025 Å" },
      { label: "B", text: "0.25 Å" },
      { label: "C", text: "2.5 Å" },
      { label: "D", text: "25 Å" },
    ],
    correctOption: "B",
    explanation: "λ_min = hc/(eV) = 1240 eV·nm / (50000 eV) = 0.0248 nm ≈ 0.25 Å.",
    difficulty: "MEDIUM",
    tags: ["x-ray", "wavelength", "cutoff"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Photoelectric Effect",
    content: "Light of wavelength 200 nm falls on a metal with work function 4.0 eV. The stopping potential is approximately: (h = 4.14×10⁻¹⁵ eV·s, c = 3×10⁸ m/s)",
    questionType: "MCQ",
    options: [
      { label: "A", text: "2.0 V" },
      { label: "B", text: "6.2 V" },
      { label: "C", text: "1.2 V" },
      { label: "D", text: "10.2 V" },
    ],
    correctOption: "A",
    explanation: "E_photon = hc/λ = 1240/200 = 6.2 eV. KE_max = 6.2 − 4.0 = 2.2 eV. Stopping potential ≈ 2.2 V ≈ 2.0 V.",
    difficulty: "MEDIUM",
    tags: ["photoelectric", "stopping potential", "work function"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Radioactivity",
    content: "Alpha particle emission from a nucleus increases its atomic number by 2 and decreases mass number by 4. Beta⁻ emission:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Increases atomic number by 1, mass number unchanged" },
      { label: "B", text: "Decreases atomic number by 1, mass number unchanged" },
      { label: "C", text: "Increases mass number by 1" },
      { label: "D", text: "No change in any number" },
    ],
    correctOption: "A",
    explanation: "Beta⁻ decay: n → p + e⁻ + anti-neutrino. One neutron becomes a proton: Z increases by 1, A remains the same.",
    difficulty: "EASY",
    tags: ["radioactivity", "beta decay", "nuclear"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Bohr Model",
    content: "According to Bohr's model, the radius of the nth orbit of hydrogen is proportional to:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "n" },
      { label: "B", text: "n²" },
      { label: "C", text: "1/n" },
      { label: "D", text: "1/n²" },
    ],
    correctOption: "B",
    explanation: "rₙ = a₀n² where a₀ = 0.529 Å (Bohr radius). So r ∝ n².",
    difficulty: "EASY",
    tags: ["bohr", "radius", "hydrogen"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Nuclear Binding Energy",
    content: "The binding energy per nucleon is maximum for:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Hydrogen" },
      { label: "B", text: "Iron (Fe-56)" },
      { label: "C", text: "Uranium" },
      { label: "D", text: "Helium" },
    ],
    correctOption: "B",
    explanation: "The binding energy per nucleon curve peaks around A = 56 (Iron). Elements near iron are most stable.",
    difficulty: "EASY",
    tags: ["binding energy", "nuclear", "stability"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Heisenberg Uncertainty",
    content: "Heisenberg's uncertainty principle states that the product of uncertainties in position and momentum is at least:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "h" },
      { label: "B", text: "h/2π" },
      { label: "C", text: "h/4π" },
      { label: "D", text: "h/2" },
    ],
    correctOption: "C",
    explanation: "Δx · Δp ≥ ℏ/2 = h/(4π).",
    difficulty: "MEDIUM",
    tags: ["uncertainty", "heisenberg", "quantum"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Compton Effect",
    content: "In Compton scattering, a photon collides with an electron at rest. After scattering, the wavelength of the photon:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Decreases" },
      { label: "B", text: "Increases" },
      { label: "C", text: "Remains the same" },
      { label: "D", text: "Depends only on angle, could decrease" },
    ],
    correctOption: "B",
    explanation: "Compton shift: Δλ = (h/mₑc)(1−cosθ) ≥ 0. The photon always loses energy, so its wavelength always increases.",
    difficulty: "MEDIUM",
    tags: ["compton", "scattering", "wavelength"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Radioactivity",
    content: "A radioactive sample has an activity of 32 μCi. After 3 half-lives, its activity will be:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "8 μCi" },
      { label: "B", text: "4 μCi" },
      { label: "C", text: "16 μCi" },
      { label: "D", text: "2 μCi" },
    ],
    correctOption: "B",
    explanation: "After 3 half-lives: A = 32 × (1/2)³ = 32/8 = 4 μCi.",
    difficulty: "EASY",
    tags: ["radioactivity", "activity", "half-life"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Photoelectric Effect",
    content: "The threshold frequency for photoelectric emission from a metal is ν₀. If light of frequency 2ν₀ is incident, the maximum kinetic energy of emitted electrons is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "hν₀" },
      { label: "B", text: "2hν₀" },
      { label: "C", text: "hν₀/2" },
      { label: "D", text: "3hν₀" },
    ],
    correctOption: "A",
    explanation: "KE_max = h(2ν₀) − hν₀ = hν₀.",
    difficulty: "MEDIUM",
    tags: ["photoelectric", "kinetic energy", "threshold"],
    source: "SEED_V1",
  },
  {
    subject: "PHYSICS", chapter: "Modern Physics", topic: "Nuclear Reactions",
    content: "In a nuclear reaction, Q-value is defined as:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "The kinetic energy of the products" },
      { label: "B", text: "(Mass of reactants − Mass of products) × c²" },
      { label: "C", text: "The binding energy of the target nucleus" },
      { label: "D", text: "The kinetic energy of the projectile" },
    ],
    correctOption: "B",
    explanation: "Q = (Δm)c² where Δm = mass of reactants − mass of products. Positive Q means exothermic reaction.",
    difficulty: "MEDIUM",
    tags: ["nuclear", "Q-value", "mass-energy"],
    source: "SEED_V1",
  },

  // ─── CHEMISTRY: Organic Chemistry (GOC) ──────────────────────────────────────
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Inductive Effect",
    content: "Which of the following groups shows the strongest +I (electron-donating inductive) effect?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "−CH₃" },
      { label: "B", text: "−C(CH₃)₃" },
      { label: "C", text: "−C₂H₅" },
      { label: "D", text: "−CH₂CH₂CH₃" },
    ],
    correctOption: "B",
    explanation: "More alkyl groups attached → stronger +I effect. −C(CH₃)₃ (tert-butyl) has 3 alkyl groups feeding electron density, making it the strongest +I group here.",
    difficulty: "MEDIUM",
    tags: ["GOC", "inductive effect", "alkyl groups"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Resonance",
    content: "Which of the following molecules shows resonance?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "CH₄" },
      { label: "B", text: "C₂H₆" },
      { label: "C", text: "Benzene (C₆H₆)" },
      { label: "D", text: "Cyclohexane" },
    ],
    correctOption: "C",
    explanation: "Benzene has delocalized π electrons spread over 6 carbons — a classic resonance structure. The others have only σ bonds with no delocalization.",
    difficulty: "EASY",
    tags: ["resonance", "benzene", "aromaticity"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Hyperconjugation",
    content: "Hyperconjugation involves the delocalization of electrons from:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Lone pair into empty p-orbital" },
      { label: "B", text: "C−H sigma bond into adjacent π or empty p-orbital" },
      { label: "C", text: "Pi bond into sigma bond" },
      { label: "D", text: "C−C bond into lone pair" },
    ],
    correctOption: "B",
    explanation: "Hyperconjugation: electrons from a C−H σ bond adjacent to a double bond or carbocation delocalize into the π* or empty p-orbital.",
    difficulty: "MEDIUM",
    tags: ["hyperconjugation", "GOC", "carbocation"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Carbocation Stability",
    content: "The correct order of carbocation stability is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Methyl > Primary > Secondary > Tertiary" },
      { label: "B", text: "Tertiary > Secondary > Primary > Methyl" },
      { label: "C", text: "Primary > Secondary > Tertiary > Methyl" },
      { label: "D", text: "Secondary > Tertiary > Primary > Methyl" },
    ],
    correctOption: "B",
    explanation: "More alkyl groups → better hyperconjugation and inductive stabilization → higher stability. Tertiary > Secondary > Primary > Methyl.",
    difficulty: "EASY",
    tags: ["carbocation", "stability", "GOC"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Aromaticity",
    content: "Which of the following is aromatic according to Hückel's rule?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Cyclobutadiene (4 π electrons)" },
      { label: "B", text: "Cyclooctatetraene (8 π electrons)" },
      { label: "C", text: "Benzene (6 π electrons)" },
      { label: "D", text: "Cyclopentadienyl cation (4 π electrons)" },
    ],
    correctOption: "C",
    explanation: "Hückel's rule: 4n+2 π electrons (n = integer) for aromaticity. Benzene has 6 = 4(1)+2 ✓. Cyclobutadiene = 4 = 4(1)+0 (antiaromatic). COT = 8 (non-planar, non-aromatic).",
    difficulty: "MEDIUM",
    tags: ["aromaticity", "huckel", "benzene"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Reaction Intermediates",
    content: "Which reaction intermediate has an electron-deficient carbon with only 6 electrons in its valence shell?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Carbanion" },
      { label: "B", text: "Free radical" },
      { label: "C", text: "Carbocation" },
      { label: "D", text: "Carbene" },
    ],
    correctOption: "C",
    explanation: "Carbocation: carbon has 3 bonds = 6 electrons, empty p-orbital. Carbanion has 8 electrons. Free radical has 7 electrons. Carbene has 6 electrons but is neutral (2 bonds + lone pair or 2 unpaired e⁻).",
    difficulty: "EASY",
    tags: ["carbocation", "intermediate", "GOC"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Isomerism",
    content: "Which type of isomerism exists between CH₃CH₂OH and CH₃OCH₃?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Chain isomerism" },
      { label: "B", text: "Position isomerism" },
      { label: "C", text: "Functional group isomerism" },
      { label: "D", text: "Metamers" },
    ],
    correctOption: "C",
    explanation: "Both have molecular formula C₂H₆O but different functional groups (alcohol vs ether). This is functional group isomerism.",
    difficulty: "EASY",
    tags: ["isomerism", "functional group", "GOC"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Electrophiles and Nucleophiles",
    content: "Which of the following is a nucleophile?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "BF₃" },
      { label: "B", text: "AlCl₃" },
      { label: "C", text: "H⁺" },
      { label: "D", text: "OH⁻" },
    ],
    correctOption: "D",
    explanation: "Nucleophiles are electron-rich species that donate electrons. OH⁻ has lone pairs to donate. BF₃, AlCl₃, H⁺ are Lewis/Brønsted acids — electrophiles.",
    difficulty: "EASY",
    tags: ["nucleophile", "electrophile", "GOC"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Resonance",
    content: "In the resonance structures of the carboxylate ion (RCOO⁻), the C−O bond order is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "1.5" },
      { label: "D", text: "0.5" },
    ],
    correctOption: "C",
    explanation: "The carboxylate ion has two equivalent C−O bonds due to resonance. Bond order = (1+2)/2 = 1.5.",
    difficulty: "MEDIUM",
    tags: ["resonance", "carboxylate", "bond order"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "IUPAC Nomenclature",
    content: "The IUPAC name of CH₃−CH(OH)−CH₂−COOH is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "3-hydroxybutanoic acid" },
      { label: "B", text: "2-methylpropanoic acid" },
      { label: "C", text: "3-hydroxy-4-methylpentanoic acid" },
      { label: "D", text: "β-hydroxybutyric acid" },
    ],
    correctOption: "A",
    explanation: "Parent chain: 4 carbons with COOH at C1. OH at C3. Name: 3-hydroxybutanoic acid.",
    difficulty: "MEDIUM",
    tags: ["IUPAC", "nomenclature", "alcohol acid"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Carbanion Stability",
    content: "Which carbanion is most stable?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "CH₃⁻" },
      { label: "B", text: "C₆H₅CH₂⁻ (benzyl)" },
      { label: "C", text: "HC≡C⁻ (alkynyl)" },
      { label: "D", text: "(CH₃)₃C⁻ (tert-butyl)" },
    ],
    correctOption: "C",
    explanation: "Alkynyl carbanion: sp carbon (50% s-character) holds electrons closer to nucleus → very stable. Benzyl is resonance-stabilized but less stable than sp carbon.",
    difficulty: "HARD",
    tags: ["carbanion", "stability", "hybridization"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Mesomeric Effect",
    content: "−NH₂ group shows which mesomeric effect?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "+M effect (electron donating by resonance)" },
      { label: "B", text: "−M effect (electron withdrawing by resonance)" },
      { label: "C", text: "No mesomeric effect" },
      { label: "D", text: "+I effect only" },
    ],
    correctOption: "A",
    explanation: "−NH₂ has a lone pair on nitrogen that can be donated to the ring/adjacent π system → +M (electron-donating mesomeric) effect.",
    difficulty: "MEDIUM",
    tags: ["mesomeric effect", "amino group", "resonance"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Free Radical",
    content: "Free radical halogenation of alkanes follows which order of reactivity?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "3° H > 2° H > 1° H" },
      { label: "B", text: "1° H > 2° H > 3° H" },
      { label: "C", text: "All H atoms are equally reactive" },
      { label: "D", text: "2° H > 3° H > 1° H" },
    ],
    correctOption: "A",
    explanation: "Tertiary free radicals are more stable (hyperconjugation and inductive effects). So tertiary H is abstracted most easily: 3° > 2° > 1°.",
    difficulty: "MEDIUM",
    tags: ["free radical", "halogenation", "reactivity"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Inductive Effect",
    content: "The pKa values of acetic acid (CH₃COOH) and trichloroacetic acid (CCl₃COOH) are 4.74 and 0.66 respectively. This is due to:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "+I effect of Cl groups increasing acidity" },
      { label: "B", text: "−I effect of Cl groups increasing acidity" },
      { label: "C", text: "+M effect of Cl" },
      { label: "D", text: "Steric effect" },
    ],
    correctOption: "B",
    explanation: "Cl is electronegative (−I effect), pulling electrons away from the carboxylate, stabilizing the anion after deprotonation → stronger acid → lower pKa.",
    difficulty: "HARD",
    tags: ["inductive effect", "acidity", "pKa", "Cl"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Organic Chemistry (GOC)", topic: "Hybridization",
    content: "The hybridization of carbon in CO₂ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "sp³" },
      { label: "B", text: "sp²" },
      { label: "C", text: "sp" },
      { label: "D", text: "sp³d" },
    ],
    correctOption: "C",
    explanation: "CO₂ is linear (O=C=O). Carbon forms 2 double bonds, no lone pairs. VSEPR: linear → sp hybridization.",
    difficulty: "EASY",
    tags: ["hybridization", "CO2", "sp"],
    source: "SEED_V1",
  },

  // ─── CHEMISTRY: Coordination Compounds ───────────────────────────────────────
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Werner's Theory",
    content: "In the complex [Co(NH₃)₅Cl]Cl₂, the coordination number of Co is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "5" },
      { label: "B", text: "6" },
      { label: "C", text: "3" },
      { label: "D", text: "7" },
    ],
    correctOption: "B",
    explanation: "Inside the coordination sphere: 5 NH₃ + 1 Cl⁻ = 6 ligands. Coordination number = 6.",
    difficulty: "EASY",
    tags: ["coordination number", "Werner", "complex"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "IUPAC Nomenclature",
    content: "The IUPAC name of [Fe(CN)₆]³⁻ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Hexacyanoferrate(II)" },
      { label: "B", text: "Hexacyanoferrate(III)" },
      { label: "C", text: "Hexacyanoiron(III)" },
      { label: "D", text: "Iron(III) hexacyanide" },
    ],
    correctOption: "B",
    explanation: "CN⁻ is cyano ligand. 6 CN⁻ = hexacyano. Fe charge: let x−6 = −3 → x = +3. Anion complex ends in -ate: hexacyanoferrate(III).",
    difficulty: "MEDIUM",
    tags: ["nomenclature", "cyanide", "iron"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Crystal Field Theory",
    content: "In an octahedral crystal field, d-orbitals split into two sets. The lower energy set (t₂g) consists of:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "dz², dx²-y²" },
      { label: "B", text: "dxy, dyz, dxz" },
      { label: "C", text: "dxy, dz², dxz" },
      { label: "D", text: "dyz, dx²-y², dxy" },
    ],
    correctOption: "B",
    explanation: "In octahedral field: t₂g (lower energy) = dxy, dyz, dxz. These point between axes, away from ligands. eg (higher) = dz², dx²-y². These point toward ligands.",
    difficulty: "MEDIUM",
    tags: ["CFT", "octahedral", "d-orbital splitting"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Isomerism",
    content: "[Co(en)₂Cl₂]⁺ exhibits which type of isomerism? (en = ethylenediamine)",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Linkage isomerism only" },
      { label: "B", text: "Geometric (cis-trans) and optical isomerism" },
      { label: "C", text: "Ionisation isomerism only" },
      { label: "D", text: "Coordination isomerism" },
    ],
    correctOption: "B",
    explanation: "cis-[Co(en)₂Cl₂]⁺ has non-superimposable mirror images → optical isomers (chiral). trans form is achiral. So both geometric and optical isomerism exist.",
    difficulty: "HARD",
    tags: ["isomerism", "optical", "geometric", "cobalt"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "EAN Rule",
    content: "The effective atomic number (EAN) of Ni in [Ni(CO)₄] is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "36" },
      { label: "B", text: "34" },
      { label: "C", text: "38" },
      { label: "D", text: "28" },
    ],
    correctOption: "A",
    explanation: "Ni(0): atomic number 28, electrons = 28. Each CO donates 2 electrons. EAN = 28 + 4×2 = 36. This follows the 18-electron rule.",
    difficulty: "MEDIUM",
    tags: ["EAN", "18-electron rule", "carbonyl"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Valence Bond Theory",
    content: "The magnetic nature of [Fe(CN)₆]⁴⁻ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Paramagnetic" },
      { label: "B", text: "Diamagnetic" },
      { label: "C", text: "Ferromagnetic" },
      { label: "D", text: "Ferrimagnetic" },
    ],
    correctOption: "B",
    explanation: "Fe²⁺ has d⁶ config. CN⁻ is a strong field ligand → low spin → all 6 d electrons pair in t₂g → no unpaired electrons → diamagnetic.",
    difficulty: "MEDIUM",
    tags: ["magnetic", "low spin", "strong field"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Ligands",
    content: "EDTA is a:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Monodentate ligand" },
      { label: "B", text: "Bidentate ligand" },
      { label: "C", text: "Tetradentate ligand" },
      { label: "D", text: "Hexadentate ligand" },
    ],
    correctOption: "D",
    explanation: "EDTA (ethylenediaminetetraacetate) has 2 N donor atoms and 4 O donor atoms = 6 binding sites → hexadentate.",
    difficulty: "EASY",
    tags: ["EDTA", "ligand", "denticity"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Crystal Field Theory",
    content: "The crystal field stabilisation energy (CFSE) for a d⁵ high spin octahedral complex is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "0 Δₒ" },
      { label: "B", text: "−2Δₒ" },
      { label: "C", text: "−4Δₒ" },
      { label: "D", text: "+2Δₒ" },
    ],
    correctOption: "A",
    explanation: "High spin d⁵: t₂g³ eg² (each orbital has 1 electron). CFSE = 3×(−0.4Δₒ) + 2×(+0.6Δₒ) = −1.2 + 1.2 = 0.",
    difficulty: "HARD",
    tags: ["CFSE", "high spin", "d5", "CFT"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Chelate Effect",
    content: "The chelate effect refers to:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "The destabilization of complexes with polydentate ligands" },
      { label: "B", text: "Enhanced stability of complexes formed with polydentate ligands" },
      { label: "C", text: "The color change when chelates form" },
      { label: "D", text: "Formation of ionic complexes only" },
    ],
    correctOption: "B",
    explanation: "Polydentate ligands form ring structures with the metal (chelates). Entropy increases on formation (multiple bonds from one ligand) → extra thermodynamic stability = chelate effect.",
    difficulty: "MEDIUM",
    tags: ["chelate effect", "stability", "polydentate"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Oxidation State",
    content: "The oxidation state of Pt in [Pt(en)Cl₂] is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "+4" },
      { label: "B", text: "+2" },
      { label: "C", text: "0" },
      { label: "D", text: "+3" },
    ],
    correctOption: "B",
    explanation: "en is neutral. 2 Cl⁻ contribute −2. Complex is neutral: x + 0 + (−2) = 0 → x = +2.",
    difficulty: "EASY",
    tags: ["oxidation state", "platinum", "complex"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Spectrochemical Series",
    content: "Arrange the following ligands in increasing order of crystal field splitting (Δ): I⁻, H₂O, CN⁻, NH₃",
    questionType: "MCQ",
    options: [
      { label: "A", text: "I⁻ < H₂O < NH₃ < CN⁻" },
      { label: "B", text: "CN⁻ < NH₃ < H₂O < I⁻" },
      { label: "C", text: "H₂O < I⁻ < NH₃ < CN⁻" },
      { label: "D", text: "NH₃ < H₂O < I⁻ < CN⁻" },
    ],
    correctOption: "A",
    explanation: "Spectrochemical series (weak → strong field): I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < CN⁻ < CO.",
    difficulty: "MEDIUM",
    tags: ["spectrochemical series", "CFT", "ligand strength"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Nomenclature",
    content: "What is the correct formula for tetraamminecopper(II) sulfate?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "[Cu(NH₃)₄]SO₄" },
      { label: "B", text: "Cu(NH₃)₄SO₄" },
      { label: "C", text: "[Cu(SO₄)(NH₃)₄]" },
      { label: "D", text: "CuSO₄·4NH₃" },
    ],
    correctOption: "A",
    explanation: "Complex cation [Cu(NH₃)₄]²⁺ with SO₄²⁻ counter ion. Formula: [Cu(NH₃)₄]SO₄.",
    difficulty: "EASY",
    tags: ["nomenclature", "copper", "formula writing"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Applications",
    content: "Cisplatin, used as an anticancer drug, has the formula:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "trans-[Pt(NH₃)₂Cl₂]" },
      { label: "B", text: "cis-[Pt(NH₃)₂Cl₂]" },
      { label: "C", text: "[Pt(NH₃)₄]Cl₂" },
      { label: "D", text: "[PtCl₄]²⁻" },
    ],
    correctOption: "B",
    explanation: "Cisplatin is cis-diamminedichloridoplatinum(II) = cis-[Pt(NH₃)₂Cl₂]. The trans isomer (transplatin) is inactive as an anticancer drug.",
    difficulty: "EASY",
    tags: ["cisplatin", "application", "geometric isomer"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Linkage Isomerism",
    content: "Which pair of complexes represents linkage isomers?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "[Co(NH₃)₅NO₂]Cl₂ and [Co(NH₃)₅ONO]Cl₂" },
      { label: "B", text: "[Co(NH₃)₅Cl]SO₄ and [Co(NH₃)₅SO₄]Cl" },
      { label: "C", text: "[Co(NH₃)₄Cl₂]Cl and [Co(NH₃)₃Cl₃]" },
      { label: "D", text: "[Cr(NH₃)₆][Co(CN)₆] and [Co(NH₃)₆][Cr(CN)₆]" },
    ],
    correctOption: "A",
    explanation: "Linkage isomers differ in which atom of an ambidentate ligand bonds to metal. NO₂⁻ can bind through N (nitro) or O (nitrito). Options A shows both binding modes.",
    difficulty: "HARD",
    tags: ["linkage isomerism", "ambidentate", "nitrite"],
    source: "SEED_V1",
  },
  {
    subject: "CHEMISTRY", chapter: "Coordination Compounds", topic: "Stability Constants",
    content: "A high stability constant (Kf) of a complex indicates:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "The complex is easily dissociated" },
      { label: "B", text: "The complex is thermodynamically unstable" },
      { label: "C", text: "The complex is thermodynamically stable" },
      { label: "D", text: "The ligands are weakly bound" },
    ],
    correctOption: "C",
    explanation: "Formation constant Kf = [complex] / [metal][ligand]ⁿ. High Kf means equilibrium lies toward complex formation → thermodynamically stable complex.",
    difficulty: "MEDIUM",
    tags: ["stability constant", "formation constant", "thermodynamics"],
    source: "SEED_V1",
  },

  // ─── MATH: Applications of Derivatives ───────────────────────────────────────
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Maxima and Minima",
    content: "The function f(x) = x³ − 3x has a local minimum at:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "x = −1" },
      { label: "B", text: "x = 0" },
      { label: "C", text: "x = 1" },
      { label: "D", text: "x = −√3" },
    ],
    correctOption: "C",
    explanation: "f'(x) = 3x²−3 = 0 → x = ±1. f''(x) = 6x. f''(1) = 6 > 0 → local min at x=1. f''(−1) = −6 < 0 → local max at x=−1.",
    difficulty: "EASY",
    tags: ["maxima minima", "critical points", "derivative"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Rate of Change",
    content: "A spherical balloon is being inflated. When the radius is 5 cm, the volume is increasing at 100 cm³/s. The rate at which the radius is increasing is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1/π cm/s" },
      { label: "B", text: "4/π cm/s" },
      { label: "C", text: "1/(π) cm/s" },
      { label: "D", text: "2/π cm/s" },
    ],
    correctOption: "A",
    explanation: "V = (4/3)πr³. dV/dt = 4πr²(dr/dt). 100 = 4π(25)(dr/dt). dr/dt = 100/(100π) = 1/π cm/s.",
    difficulty: "MEDIUM",
    tags: ["rate of change", "sphere", "related rates"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Tangent and Normal",
    content: "The slope of the tangent to y = x³ at the point (1, 1) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "3" },
      { label: "D", text: "6" },
    ],
    correctOption: "C",
    explanation: "dy/dx = 3x². At x = 1: slope = 3(1)² = 3.",
    difficulty: "EASY",
    tags: ["tangent", "slope", "derivative"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Increasing/Decreasing Functions",
    content: "f(x) = 2x³ − 9x² + 12x − 4 is increasing when:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "x < 1 or x > 2" },
      { label: "B", text: "1 < x < 2" },
      { label: "C", text: "x > 0" },
      { label: "D", text: "All x" },
    ],
    correctOption: "A",
    explanation: "f'(x) = 6x²−18x+12 = 6(x²−3x+2) = 6(x−1)(x−2). f'>0 when x<1 or x>2.",
    difficulty: "MEDIUM",
    tags: ["increasing", "decreasing", "derivative"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Maxima and Minima",
    content: "The maximum value of f(x) = sin(x) + cos(x) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "√2" },
      { label: "D", text: "1/√2" },
    ],
    correctOption: "C",
    explanation: "f(x) = √2 sin(x + π/4). Maximum value = √2.",
    difficulty: "EASY",
    tags: ["maxima", "trigonometric", "sin cos"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Mean Value Theorem",
    content: "Rolle's theorem requires that f be continuous on [a,b], differentiable on (a,b), and:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "f(a) > f(b)" },
      { label: "B", text: "f(a) = f(b)" },
      { label: "C", text: "f(a) < f(b)" },
      { label: "D", text: "f'(a) = f'(b)" },
    ],
    correctOption: "B",
    explanation: "Rolle's theorem: f(a) = f(b). Then ∃ c ∈ (a,b) such that f'(c) = 0.",
    difficulty: "EASY",
    tags: ["Rolle's theorem", "mean value theorem", "conditions"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Approximation",
    content: "Using differentials, the approximate value of √(4.01) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "2.001" },
      { label: "B", text: "2.0025" },
      { label: "C", text: "2.01" },
      { label: "D", text: "2.005" },
    ],
    correctOption: "B",
    explanation: "Let f(x) = √x. f'(x) = 1/(2√x). At x=4: f'(4) = 1/4. Δx = 0.01. Δy ≈ f'(4)·Δx = 0.01/4 = 0.0025. √(4.01) ≈ 2 + 0.0025 = 2.0025.",
    difficulty: "MEDIUM",
    tags: ["approximation", "differentials", "sqrt"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Maxima and Minima",
    content: "A rectangle has perimeter 40 cm. What dimensions maximize its area?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "10 cm × 10 cm" },
      { label: "B", text: "8 cm × 12 cm" },
      { label: "C", text: "5 cm × 15 cm" },
      { label: "D", text: "4 cm × 16 cm" },
    ],
    correctOption: "A",
    explanation: "P = 2(l+w) = 40 → l+w = 20. Area = lw. By AM-GM, lw is maximized when l = w = 10.",
    difficulty: "MEDIUM",
    tags: ["optimization", "rectangle", "maxima"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Concavity",
    content: "f(x) = x⁴ − 4x³. The inflection point(s) are at:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "x = 0 only" },
      { label: "B", text: "x = 2 only" },
      { label: "C", text: "x = 0 and x = 2" },
      { label: "D", text: "x = 1" },
    ],
    correctOption: "C",
    explanation: "f''(x) = 12x²−24x = 12x(x−2) = 0 → x=0 or x=2. f'' changes sign at both points → both are inflection points.",
    difficulty: "HARD",
    tags: ["inflection point", "concavity", "second derivative"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Rate of Change",
    content: "The length of a side of a square is increasing at 2 cm/s. The rate at which the area is increasing when the side is 5 cm is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "10 cm²/s" },
      { label: "B", text: "20 cm²/s" },
      { label: "C", text: "4 cm²/s" },
      { label: "D", text: "25 cm²/s" },
    ],
    correctOption: "B",
    explanation: "A = s². dA/dt = 2s(ds/dt) = 2(5)(2) = 20 cm²/s.",
    difficulty: "EASY",
    tags: ["rate of change", "area", "square"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Tangent and Normal",
    content: "The equation of the normal to y = x² at (2, 4) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "y − 4 = 4(x − 2)" },
      { label: "B", text: "x + 4y = 18" },
      { label: "C", text: "4x + y = 12" },
      { label: "D", text: "y = −x/4 + 9/2" },
    ],
    correctOption: "B",
    explanation: "dy/dx = 2x. At (2,4): slope of tangent = 4. Slope of normal = −1/4. Normal: y−4 = −(1/4)(x−2) → 4y−16 = −x+2 → x+4y = 18.",
    difficulty: "MEDIUM",
    tags: ["normal", "tangent", "parabola"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "LHopital Rule",
    content: "lim(x→0) (sin x − x) / x³ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "0" },
      { label: "B", text: "1/6" },
      { label: "C", text: "−1/6" },
      { label: "D", text: "1" },
    ],
    correctOption: "C",
    explanation: "Using Taylor series: sin x = x − x³/6 + ... So sin x − x = −x³/6 + ... Dividing by x³: limit = −1/6.",
    difficulty: "HARD",
    tags: ["L'Hopital", "limits", "Taylor series"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Maxima and Minima",
    content: "What is the minimum value of f(x) = x + 1/x for x > 0?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "0" },
      { label: "B", text: "1" },
      { label: "C", text: "2" },
      { label: "D", text: "4" },
    ],
    correctOption: "C",
    explanation: "f'(x) = 1 − 1/x² = 0 → x = 1. f''(1) = 2 > 0 → min. f(1) = 1+1 = 2. (Also by AM-GM: x+1/x ≥ 2√(x·1/x) = 2.)",
    difficulty: "EASY",
    tags: ["minimum", "AM-GM", "rational function"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Increasing/Decreasing Functions",
    content: "At a critical point where f'(c) = 0 and f''(c) = 0, we can conclude:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "c is a local maximum" },
      { label: "B", text: "c is a local minimum" },
      { label: "C", text: "c is an inflection point" },
      { label: "D", text: "No conclusion from second derivative test alone" },
    ],
    correctOption: "D",
    explanation: "Second derivative test is inconclusive when f''(c) = 0. Need higher-order derivatives or sign change of f' to determine nature of c.",
    difficulty: "MEDIUM",
    tags: ["second derivative test", "inconclusive", "critical point"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Applications of Derivatives", topic: "Mean Value Theorem",
    content: "For f(x) = x² on [1,3], the value of c guaranteed by LMVT is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "2" },
      { label: "C", text: "√3" },
      { label: "D", text: "3" },
    ],
    correctOption: "B",
    explanation: "LMVT: f'(c) = [f(3)−f(1)]/(3−1) = (9−1)/2 = 4. f'(x) = 2x → 2c = 4 → c = 2.",
    difficulty: "EASY",
    tags: ["LMVT", "mean value theorem", "parabola"],
    source: "SEED_V1",
  },

  // ─── MATH: Complex Numbers ────────────────────────────────────────────────────
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Basic Operations",
    content: "The value of i¹⁰⁰ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "i" },
      { label: "B", text: "−1" },
      { label: "C", text: "1" },
      { label: "D", text: "−i" },
    ],
    correctOption: "C",
    explanation: "i¹ = i, i² = −1, i³ = −i, i⁴ = 1. The cycle repeats every 4. 100 = 4×25, so i¹⁰⁰ = (i⁴)²⁵ = 1.",
    difficulty: "EASY",
    tags: ["powers of i", "cycle", "complex numbers"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Modulus and Argument",
    content: "The modulus of (3 + 4i) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "5" },
      { label: "C", text: "25" },
      { label: "D", text: "√7" },
    ],
    correctOption: "B",
    explanation: "|3+4i| = √(3² + 4²) = √(9+16) = √25 = 5.",
    difficulty: "EASY",
    tags: ["modulus", "complex number", "Pythagoras"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Argand Plane",
    content: "The argument (principal) of −1 + i is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "π/4" },
      { label: "B", text: "3π/4" },
      { label: "C", text: "−3π/4" },
      { label: "D", text: "5π/4" },
    ],
    correctOption: "B",
    explanation: "−1+i is in second quadrant. Basic angle = arctan(1/1) = π/4. Argument = π − π/4 = 3π/4.",
    difficulty: "MEDIUM",
    tags: ["argument", "principal value", "quadrant"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Polar Form",
    content: "The polar form of (1 + i) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "√2 (cos π/4 + i sin π/4)" },
      { label: "B", text: "√2 (cos π/2 + i sin π/2)" },
      { label: "C", text: "2 (cos π/4 + i sin π/4)" },
      { label: "D", text: "(cos π/4 + i sin π/4)" },
    ],
    correctOption: "A",
    explanation: "r = |1+i| = √2. arg = arctan(1/1) = π/4. Polar: √2 (cos π/4 + i sin π/4).",
    difficulty: "EASY",
    tags: ["polar form", "modulus-argument", "complex"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Conjugate",
    content: "If z = 3 − 4i, then z·z̄ equals:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "25" },
      { label: "C", text: "0" },
      { label: "D", text: "−7" },
    ],
    correctOption: "B",
    explanation: "z·z̄ = |z|² = 3²+4² = 9+16 = 25.",
    difficulty: "EASY",
    tags: ["conjugate", "modulus", "product"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "De Moivre's Theorem",
    content: "Using De Moivre's theorem, (cos θ + i sin θ)ⁿ equals:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "cos(nθ) − i sin(nθ)" },
      { label: "B", text: "cos(nθ) + i sin(nθ)" },
      { label: "C", text: "n cos θ + in sin θ" },
      { label: "D", text: "cos(θ/n) + i sin(θ/n)" },
    ],
    correctOption: "B",
    explanation: "De Moivre's theorem: (cos θ + i sin θ)ⁿ = cos(nθ) + i sin(nθ) for integer n.",
    difficulty: "EASY",
    tags: ["De Moivre", "theorem", "power"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Cube Roots of Unity",
    content: "If ω is a complex cube root of unity, then 1 + ω + ω² equals:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "ω" },
      { label: "C", text: "0" },
      { label: "D", text: "1" },
    ],
    correctOption: "C",
    explanation: "The three cube roots of unity are 1, ω, ω². Their sum = 1 + ω + ω² = 0 (roots of x³ − 1 = 0 → sum of roots = 0).",
    difficulty: "EASY",
    tags: ["cube roots", "unity", "omega"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Locus",
    content: "The locus of z such that |z − 2| = 3 represents a:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "Circle of radius 3 centred at (2, 0)" },
      { label: "B", text: "Circle of radius 2 centred at (3, 0)" },
      { label: "C", text: "Line x = 2" },
      { label: "D", text: "Ellipse" },
    ],
    correctOption: "A",
    explanation: "|z − 2| = 3 means distance from z to the point (2,0) in the Argand plane is 3. This is a circle, centre (2,0), radius 3.",
    difficulty: "EASY",
    tags: ["locus", "circle", "modulus"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Division",
    content: "The value of (2+3i)/(1−2i) is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "−4/5 + 7i/5" },
      { label: "B", text: "4/5 + 7i/5" },
      { label: "C", text: "−4/5 − 7i/5" },
      { label: "D", text: "8/5 + i/5" },
    ],
    correctOption: "A",
    explanation: "Multiply numerator and denominator by conjugate (1+2i): (2+3i)(1+2i)/[(1−2i)(1+2i)] = (2+4i+3i+6i²)/(1+4) = (2+7i−6)/5 = (−4+7i)/5.",
    difficulty: "MEDIUM",
    tags: ["division", "conjugate multiply", "complex"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Inequality",
    content: "For complex numbers z₁ and z₂, which inequality always holds?",
    questionType: "MCQ",
    options: [
      { label: "A", text: "|z₁ + z₂| ≤ |z₁| + |z₂| (triangle inequality)" },
      { label: "B", text: "|z₁ + z₂| ≥ |z₁| + |z₂|" },
      { label: "C", text: "|z₁ + z₂| = |z₁| + |z₂|" },
      { label: "D", text: "|z₁ − z₂| = |z₁| − |z₂|" },
    ],
    correctOption: "A",
    explanation: "Triangle inequality for complex numbers: |z₁+z₂| ≤ |z₁|+|z₂|. Equality when z₁ and z₂ have same argument.",
    difficulty: "EASY",
    tags: ["triangle inequality", "modulus", "properties"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Roots of Equation",
    content: "The equation z² + 1 = 0 has roots:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "z = 1 and z = −1" },
      { label: "B", text: "z = i and z = −i" },
      { label: "C", text: "z = 1+i and z = 1−i" },
      { label: "D", text: "No roots" },
    ],
    correctOption: "B",
    explanation: "z² = −1 → z = ±√(−1) = ±i.",
    difficulty: "EASY",
    tags: ["roots", "quadratic", "imaginary"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "De Moivre's Theorem",
    content: "The value of (1+i)⁸ is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "16" },
      { label: "B", text: "16i" },
      { label: "C", text: "−16" },
      { label: "D", text: "8" },
    ],
    correctOption: "A",
    explanation: "(1+i) = √2·e^(iπ/4). (1+i)⁸ = (√2)⁸ · e^(i·2π) = 16 · 1 = 16.",
    difficulty: "MEDIUM",
    tags: ["De Moivre", "power", "polar"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Argument Properties",
    content: "arg(z₁ · z₂) equals:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "arg(z₁) × arg(z₂)" },
      { label: "B", text: "arg(z₁) + arg(z₂)" },
      { label: "C", text: "arg(z₁) − arg(z₂)" },
      { label: "D", text: "arg(z₁) / arg(z₂)" },
    ],
    correctOption: "B",
    explanation: "In polar form z = r·e^(iθ). z₁·z₂ = r₁r₂·e^{i(θ₁+θ₂)}. Argument of product = sum of arguments (mod 2π).",
    difficulty: "EASY",
    tags: ["argument", "product", "properties"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "Locus",
    content: "The locus of z where arg(z) = π/4 represents:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "A circle" },
      { label: "B", text: "A ray from origin at 45° in the first quadrant" },
      { label: "C", text: "The line y = x for all x" },
      { label: "D", text: "A semicircle" },
    ],
    correctOption: "B",
    explanation: "arg(z) = π/4 means the angle the line from origin to z makes with positive x-axis is 45°. This is a ray (half-line) from origin, not including origin.",
    difficulty: "MEDIUM",
    tags: ["argument", "locus", "ray"],
    source: "SEED_V1",
  },
  {
    subject: "MATH", chapter: "Complex Numbers", topic: "nth Roots",
    content: "The number of distinct nth roots of unity is:",
    questionType: "MCQ",
    options: [
      { label: "A", text: "n − 1" },
      { label: "B", text: "n" },
      { label: "C", text: "n + 1" },
      { label: "D", text: "2" },
    ],
    correctOption: "B",
    explanation: "The equation zⁿ = 1 has exactly n solutions (roots of unity): e^(2πik/n) for k = 0, 1, ..., n−1.",
    difficulty: "EASY",
    tags: ["nth roots", "unity", "count"],
    source: "SEED_V1",
  },
];

async function main() {
  console.log("Seeding question bank...");

  // Clear existing seed questions
  await prisma.question.deleteMany({ where: { source: "SEED_V1" } });

  const created = await prisma.question.createMany({
    data: questions.map((q) => ({
      subject: q.subject,
      chapter: q.chapter,
      topic: q.topic,
      content: q.content,
      questionType: q.questionType,
      options: q.options,
      correctOption: q.correctOption,
      explanation: q.explanation,
      difficulty: q.difficulty,
      tags: q.tags,
      source: q.source,
    })),
  });

  console.log(`✅ Created ${created.count} questions across 6 chapters.`);

  // Log breakdown
  const breakdown = await prisma.question.groupBy({
    by: ["subject", "chapter"],
    _count: { _all: true },
    where: { source: "SEED_V1" },
    orderBy: [{ subject: "asc" }, { chapter: "asc" }],
  });

  for (const row of breakdown) {
    console.log(`   ${row.subject} / ${row.chapter}: ${row._count._all} questions`);
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
